import type { MarketProfile } from '@/core/types';

export const MARKET_PROFILES: MarketProfile[] = [
  {
    id: 'japan',
    market: '日本',
    language: '日语',
    locale: 'ja-JP',
    visualTheme: 'violet',
    avatarTheme: 'Editorial precision',
    stageTheme: 'Tokyo product studio',
    platformName: 'MIRAI STREAM',
    ttsVoicePreference: ['Kyoko', 'Nanami', 'Japanese'],
    subtitleStyle: 'precision-center',
    priority: 1,
    targetKbps: 2400,
    minimumStableKbps: 850,
    viewers: 9316,
  },
  {
    id: 'latam',
    market: '拉美',
    language: '西班牙语',
    locale: 'es-MX',
    visualTheme: 'amber',
    avatarTheme: 'Warm commerce',
    stageTheme: 'Mexico City live studio',
    platformName: 'ÓRBITA LIVE',
    ttsVoicePreference: ['Paulina', 'Monica', 'Spanish'],
    subtitleStyle: 'editorial-bottom',
    priority: 2,
    targetKbps: 2100,
    minimumStableKbps: 700,
    viewers: 15879,
  },
  {
    id: 'india',
    market: '印度',
    language: '英语',
    locale: 'en-IN',
    visualTheme: 'teal',
    avatarTheme: 'Contemporary retail',
    stageTheme: 'Mumbai social commerce studio',
    platformName: 'NAYA LIVE',
    ttsVoicePreference: ['Rishi', 'Veena', 'English India'],
    subtitleStyle: 'minimal-left',
    priority: 3,
    targetKbps: 1800,
    minimumStableKbps: 560,
    viewers: 12842,
  },
];
