import type { MarketProfile } from '@/core/types';

export const MARKET_PROFILES: MarketProfile[] = [
  {
    id: 'north-america',
    market: 'North America',
    language: 'English',
    locale: 'en-US',
    visualTheme: 'cobalt',
    avatarTheme: 'Astra / Graphite',
    stageTheme: 'Cobalt Broadcast Suite',
    platformName: 'NOVA LIVE',
    ttsVoicePreference: ['Samantha', 'Ava', 'English'],
    subtitleStyle: 'minimal-left',
    priority: 1,
    targetKbps: 2400,
    minimumStableKbps: 850,
    viewers: 12842,
  },
  {
    id: 'japan',
    market: 'Japan',
    language: '日本語',
    locale: 'ja-JP',
    visualTheme: 'violet',
    avatarTheme: 'Rei / Pearl',
    stageTheme: 'Violet Light Frame',
    platformName: 'MIRAI STREAM',
    ttsVoicePreference: ['Kyoko', 'Nanami', 'Japanese'],
    subtitleStyle: 'precision-center',
    priority: 2,
    targetKbps: 2100,
    minimumStableKbps: 700,
    viewers: 9316,
  },
  {
    id: 'spanish',
    market: 'LATAM + Spain',
    language: 'Español',
    locale: 'es-ES',
    visualTheme: 'amber',
    avatarTheme: 'Sol / Obsidian',
    stageTheme: 'Amber Horizon Studio',
    platformName: 'ÓRBITA LIVE',
    ttsVoicePreference: ['Monica', 'Paulina', 'Spanish'],
    subtitleStyle: 'editorial-bottom',
    priority: 3,
    targetKbps: 1800,
    minimumStableKbps: 560,
    viewers: 15879,
  },
];
